addEventListener('fetch', event => {
  event.respondWith(
    handleRequest(event.request).catch(
      err => new Response(err.stack, { status: 500 }),
    ),
  );
});

async function handleRequest(request) {
  const { origin, pathname } = new URL(request.url);

  if (pathname == '/' || pathname == '/txt/' || pathname == '/txt/index.html') {
    return Response.redirect(origin + '/txt/hutrua.txt', 301);
  }

  if (pathname.startsWith('/txt/') && pathname.endsWith('.txt')) {
    let name = pathname.substr(5);
    return handleTxt(name);
  }

  return handleTxt('404.txt');
}

function html_template(content) {
  let txt = content.txt.split('\n');
  for (let i = 0; i < txt.length; i++) {
    txt[i] = '<p>' + txt[i] + '</p>';
  }
  txt = txt.join('\n');
  return `<!DOCTYPE html>
<html>
<head>
  <title>${content.name}</title>
</head>
<body>
  <h1>${content.name}</h1>
  ${txt}
  <p style='color:grey;font-size:0.7em;'>This page is generated by Cloudflare Workers.</p>
</body>
</html>`;
}

async function handleTxt(name) {
  let txt = await TXT.get(name);
  if (txt == null) {
    txt = '404 not found';
  }
  let content = { name: name, txt: txt};
  return new Response(html_template(content), {
    headers: { 'content-type': 'text/html;charset=UTF-8' },
  });
}
